<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_tanggalPendiriBadanUsaha</name>
   <tag></tag>
   <elementGuidId>80ed0476-eb2f-408b-ba85-bbf1f3f5db79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div/main/div/div/div[4]/div[2]/div/div/div[2]/div/form/div[1]/div[3]/div[2]/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
