<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_year</name>
   <tag></tag>
   <elementGuidId>7c66a3b4-833f-4317-af8e-8fa4dd606b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div/main/div/div/div[4]/div[2]/div/div/div[2]/div/form/div[1]/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div[1]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
