<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validasiNomorRekSumberDana</name>
   <tag></tag>
   <elementGuidId>463e3a1b-b8ee-46b7-a438-5e3b1f742c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div/div/form/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4d4db2ea-2ff8-4a2f-83ca-246cfe098b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 a-text-style #7B87AF 400 css-srw6u7</value>
      <webElementGuid>b983998d-615c-4526-b913-8b48415546de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1401300020551</value>
      <webElementGuid>22279dd9-83b6-4a6d-8bef-c4053e1ffd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-uwwqev&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/form[1]/div[@class=&quot;css-1v8gcgw&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-ojb6vh&quot;]/div[@class=&quot;css-3iztaj&quot;]/div[@class=&quot;css-1xhj18k&quot;]/div[@class=&quot;css-celn7d&quot;]/div[@class=&quot;css-aebxwm&quot;]/div[@class=&quot;css-aebxwm&quot;]/div[@class=&quot;css-1n98ms2&quot;]/div[@class=&quot;css-12a0i14&quot;]/div[1]/div[@class=&quot;css-1afwwzv&quot;]/div[@class=&quot;css-15vhhhd&quot;]/div[@class=&quot;css-9tjvyk&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body2 a-text-style #7B87AF 400 css-srw6u7&quot;]</value>
      <webElementGuid>bc6ed5b0-e24e-47f3-aa6b-fbdb4e0d552c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/form/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div/p[2]</value>
      <webElementGuid>5ad3441c-d3c6-437b-aa42-09cb024cd918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[3]</value>
      <webElementGuid>871a8cbf-eaed-4d37-990d-80b5ce9805c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::p[9]</value>
      <webElementGuid>a531420f-ad50-40bc-a3be-f8dff5486e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::p[10]</value>
      <webElementGuid>f220d472-eb7e-41c4-acb6-aaf38c538a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1401300020551']/parent::*</value>
      <webElementGuid>389ef5de-7bb6-4bb2-a0d7-b2935514cd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div/p[2]</value>
      <webElementGuid>ea96beaa-2c4c-45aa-b818-2e92b93764ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1401300020551' or . = '1401300020551')]</value>
      <webElementGuid>ba3d338f-bf86-44a9-bd3e-00dac594e019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
