<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validasiRekeningTujuan</name>
   <tag></tag>
   <elementGuidId>45c84176-acb3-439a-bd73-cb1cf9d25344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div/div/form/div/div[2]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45f17d84-d3a8-409f-822b-6fdb17c597c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 a-text-style #374062 400 css-mr1cwf</value>
      <webElementGuid>7775df52-bd99-460a-bfd2-0e3e7375b4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12321321321321</value>
      <webElementGuid>d4fdfe54-84d9-4fa7-b37c-c09775512b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiScopedCssBaseline-root css-y57rlh&quot;]/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-jmbm5p&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;css-uwwqev&quot;]/div[@class=&quot;css-1v8gcgw&quot;]/form[1]/div[@class=&quot;css-1v8gcgw&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-ojb6vh&quot;]/div[@class=&quot;css-3iztaj&quot;]/div[@class=&quot;css-1xhj18k&quot;]/div[@class=&quot;css-celn7d&quot;]/div[@class=&quot;css-aebxwm&quot;]/div[@class=&quot;css-5aq423&quot;]/div[@class=&quot;css-12a0i14&quot;]/div[1]/div[@class=&quot;css-8k8r3y&quot;]/div[@class=&quot;css-1rqlbw1&quot;]/div[@class=&quot;css-9tjvyk&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body2 a-text-style #374062 400 css-mr1cwf&quot;]</value>
      <webElementGuid>13c05b37-52ad-466c-ae29-0919b47d32b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/form/div/div[2]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div/p</value>
      <webElementGuid>be1c28eb-244e-42bc-84cc-ea32ad7fa798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[6]</value>
      <webElementGuid>12869370-ecd7-422f-89e4-1c01bdd8cc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::p[6]</value>
      <webElementGuid>4ed752bc-4415-424b-bcf9-3b414d1baa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::p[7]</value>
      <webElementGuid>bf0bfa6d-e485-4537-9990-67b64e59ce91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12321321321321']/parent::*</value>
      <webElementGuid>ad248b94-b357-4caa-9c73-851f087a947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div/div/div/div/p</value>
      <webElementGuid>cd0edc57-1818-4d23-a9f4-9b33924a6881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '12321321321321' or . = '12321321321321')]</value>
      <webElementGuid>993bfbcc-850f-4b2d-81de-0960b3d5342d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
