<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bilCode2</name>
   <tag></tag>
   <elementGuidId>e51b2433-67c9-47d3-9495-4f680a4ce6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bilCode2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Kode Billing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e70fcdb-d220-4ba2-9de3-c2bb647ca553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>650fcef0-e015-4b90-a1c1-f59fdd15193f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d31a14d9-3b6a-44e2-9fb0-99d4ac57ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bilCode2</value>
      <webElementGuid>1561ac60-e09d-466c-8eca-f885be1382ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kode Billing</value>
      <webElementGuid>84fcd451-fbba-4843-a41e-4a820a23cacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6afc9b6b-f8c1-465f-8821-b0ea0d6127db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>f96af94e-7c53-4719-b7cd-f8d73675004a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabpanel-1&quot;)/div[@class=&quot;css-1h2pirz&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root a-input-text sm css-2ypjkg&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl css-xw1gz&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq&quot;]</value>
      <webElementGuid>b401a73f-7882-4e72-a6b4-dbb04c000d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[2]</value>
      <webElementGuid>08d72b6a-cb17-474f-96ae-04773b8fc452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-1']/div/div[2]/div/input</value>
      <webElementGuid>f9fe4bb9-c0db-4f6a-99d0-7f66ff59eecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>320a742e-5175-45ee-b49a-fbe5b6f992a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bilCode2' and @placeholder = 'Masukkan Kode Billing' and @type = 'text']</value>
      <webElementGuid>b37b48e9-9d8b-4bcc-8ed1-01ee01a14670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
