<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Grup Pembayaran Gaji</name>
   <tag></tag>
   <elementGuidId>64c556fd-f5a6-434f-9d9b-313e5211b882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9213a30-73a7-418f-99fd-e0dc9471f457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary MuiTab-fullWidth css-ytlln2</value>
      <webElementGuid>1e15d01a-ec98-4bb3-b6d8-dc096e5380a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7c4cdced-143f-48c8-b776-fd291bcba61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcf532b3-b54e-4bd2-bea6-3b26f6b7e470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>438b1dcc-fda1-4c9a-808f-b3ae3b453b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c0deb45-97e2-44f3-8c42-8dd63e586a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1</value>
      <webElementGuid>4932c6b4-7299-4eb5-8f45-f18818da25f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabpanel-1</value>
      <webElementGuid>d037e946-bef0-485a-b5f4-9fe9b032ab1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grup Pembayaran Gaji</value>
      <webElementGuid>5f640575-913f-454e-9182-0c8711d0aacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)</value>
      <webElementGuid>d6587331-166c-48b1-abb1-9bdfea02b721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab-1']</value>
      <webElementGuid>1c22ef15-d415-4583-9a80-9b10707535b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>28589050-8c1b-4db7-b0a9-dd6db46dbf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengecekan Rekening'])[1]/following::button[1]</value>
      <webElementGuid>4d81694f-bdf0-42be-89ae-8293d1b28d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Format Dokumen'])[1]/preceding::button[1]</value>
      <webElementGuid>1cfb4de0-f904-49eb-b039-ee58c1b04b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::button[2]</value>
      <webElementGuid>a0212447-d806-418b-9f3a-778666aaa247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grup Pembayaran Gaji']/parent::*</value>
      <webElementGuid>34d9006a-1e31-4e40-ae64-36eb9aa6902e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>d67dd817-901d-4f28-95af-49e3bf29f498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'tab-1' and (text() = 'Grup Pembayaran Gaji' or . = 'Grup Pembayaran Gaji')]</value>
      <webElementGuid>d29917cc-264e-4e57-b5e3-77e351a8b201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
