<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Trashbin</name>
   <tag></tag>
   <elementGuidId>6ace2ddb-ac9a-49ca-ada8-73e22c873c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div/form/div[1]/div/div[4]/div[2]/div/div[3]/button/span[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>04f68098-58bb-4a81-a397-26db1144b8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M2 4.5h1.333m0 0H14m-10.667 0v9.334a1.333 1.333 0 001.334 1.333h6.666a1.333 1.333 0 001.334-1.333V4.501H3.333zm2 0V3.168a1.333 1.333 0 011.334-1.333h2.666a1.333 1.333 0 011.334 1.333v1.334m-4 3.333v4m2.666-4v4</value>
      <webElementGuid>c420c2ae-f38b-42fb-9869-ce0f7153f096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#D14848</value>
      <webElementGuid>31acdf66-29b0-43c1-a99a-ef536eec7d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a1b1a542-9de3-4d69-878c-2aca5c088157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>162600bd-0621-4952-a13f-5fd9d220a7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d53fc9c0-2b75-4f7c-a3ce-cab6d693977c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root m-popup MuiModal-root css-w5qpb1&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-uhb5lp&quot;]/form[1]/div[@class=&quot;MuiDialogContent-root css-1ty026z&quot;]/div[@class=&quot;css-1ofqig9&quot;]/div[@class=&quot;css-1qrumi8&quot;]/div[@class=&quot;false css-1ftmuqb&quot;]/div[@class=&quot;css-ueohkx&quot;]/div[@class=&quot;m-action-button css-8jts0n&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-disableElevation MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-disableElevation a-button text sm text-variant css-45qc2l&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-text css-1uk1gs8&quot;]/div[@class=&quot;css-1vd84sn&quot;]/svg[@class=&quot;MuiSvgIcon-root MuiSvgIcon-fontSizeMedium a-icon icon-remove custom #D14848 lg sm css-1kuv8bg&quot;]/g[1]/path[1]</value>
      <webElementGuid>abc19302-b38a-4def-987b-146d4153adc7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
