<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_year</name>
   <tag></tag>
   <elementGuidId>bbaa9d02-e32a-4f53-bf8a-25a7b8bf0c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div/main/div/div/div[4]/div[2]/div/div/div[2]/div/form/div[2]/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div[1]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
